version: "3"

services:
  web:
    build: .
    container_name: test_deploy_web
    command: gunicorn webhookml.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app/
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    container_name: test_deploy_nginx
    ports:
      - 80:80
    depends_on:
      - web
