# Generated by Django 2.2 on 2021-11-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeWebhookMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text='Cuando se recibio el evento.')),
                ('payload', models.TextField(default=None, help_text='Texto Json del evento.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/', verbose_name='Documento')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Documento subido',
                'verbose_name_plural': 'Documentos subidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItemsMercadoLibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id_mercadolibre', models.CharField(max_length=70)),
                ('sending', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenMercadoLibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('token_type', models.CharField(max_length=100)),
                ('expires_in', models.CharField(max_length=50)),
                ('scope', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('refresh_token', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMercadoLibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('client_secret', models.CharField(max_length=50)),
                ('redirect_uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemSellMercadoLibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_mercadolibre', models.CharField(max_length=300)),
                ('item_name_mercadolibre', models.CharField(max_length=300)),
                ('item_quatity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, default=0.01, max_digits=9)),
                ('payment_id', models.CharField(max_length=300)),
                ('received_at', models.DateTimeField(help_text='When we received the event.')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=200)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OrderItemsMercadoLibre')),
            ],
        ),
        migrations.AddIndex(
            model_name='acmewebhookmessage',
            index=models.Index(fields=['received_at'], name='core_acmewe_receive_3bfdb8_idx'),
        ),
    ]
