# Generated by Django 2.2 on 2021-12-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsmercadolibre',
            name='response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitemsmercadolibre',
            name='xmlresponse',
            field=models.TextField(help_text='Texto Json del evento.', null=True),
        ),
    ]
