# Generated by Django 2.2 on 2022-02-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220208_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_brand', models.CharField(max_length=200, verbose_name='Nombre completo de la marca')),
                ('short_brand', models.CharField(max_length=100, verbose_name='Nombre corto de la marca')),
            ],
        ),
    ]
